name: Deploy Buoy Report (to DigitalOcean)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js (match local dev version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm ci --omit=dev

      # Build SPA
      - name: Build SPA
        run: npm run build

      # Add SSH key for server
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 6 Deploy files and restart server
      - name: Deploy to DigitalOcean
        run: |
          # Copy server code + built assets to droplet
          # TODO: move all server stuff into a server directory and everything else into a static dir.
          scp -r \
            package.json package-lock.json app.js dist/ migrations/ routes/ services/ static/ views/   \
            root@137.184.127.160:/home/ubuntu/buoyreport/

          # SSH into droplet to install deps & reload PM2
          ssh root@137.184.127.160 << 'EOF'
            set -e
            cd /home/ubuntu/buoyreport

            # Install production dependencies
            npm ci --omit=dev

            # Reload Node API in PM2
            pm2 reload buoyreport --update-env || pm2 start app.js --name buoyreport
          EOF
